### PR TITLE
fix: prevent new characters from joining lfg channel before others

### PR DESCRIPTION
**Pull request by juemrami**
**Related Issues**
  - #247
 
**Note**: This only fixes the issue for newly created characters. For existing characters all you have to do is reorder the channels in the blizzard chat settings.

fix output

### CODE REVIEW

**Comment by Vysci** [comment]
I would play around with this version longer. I did the same thing before and it felt like it made the problem way worse when using another addon that joins a chat channel

**Comment by juemrami** [comment]
alright thanks for the heads up. I found another addon that joins a channel as well and was testing around, i couldnt get my updated fix to error out or anything. 

(without checking specifically for server channels)

(checking for general/defense channels before joining)


Do you remember in what way it was made "worse" so i can test against that?

**Comment by Vysci** [comment]
Sorry by making it worse I mean that it would occur more frequently for some reason. I don’t mean that it was the fault of BB, but more so that chat channels in general would get shuffled more often with the change then without. 

Like I can go days/weeks/months without seeing shuffling but with the change it would happen on every logout. Again not necessarily due to BB but it would probably get blamed

**Comment by juemrami** [comment]
Alright i think boiled the issue down. 

How expected is the behavior of the addon leaving the "LookingForGroup" channel every time a character logs out? In other words, if one logs in on a character with the addon enabled and it connects to the "LookingForGroup" channel how many users expect that when they logout and disable the addon for that character, they will not be connected to the "LookingForGroup" channel on next login?

That is the current behavior of the addon since the `JoinChannelByName` joins a channel as a ["Temporary" channel](https://warcraft.wiki.gg/wiki/API_JoinTemporaryChannel). 

This is what is causing the addon always prefer lowest open index when joining "LookingForGroup", even if the user specifies a specific index as i suggested in #247, that index does not get saved for the a temporary channel.

The indices for permanent channels however are saved. 

When a user creates a character and logs in, if they watch more than ~15 seconds of the intro cut-scene, the game client loads all addons before it attempts to connect the character to the default permanent channels, "General", "Trade", "LocalDefense", in that order. This means that the `GBB.JoinLFG` function creates a temporary connection to the "LookingForGroup" channel before the character connects to the permanent server channels. As a result their indices get pushed to `2="General", 3= "Trade", 4="LocalDefense"` and since they're permanent channels their indices are remembered by the server. 

So, when a character logs out and is disconnected from the "LookingForGroup" channel, even if they disable the addon, the next time that character logs in the server will connect to `2="General", 3= "Trade", 4="LocalDefense"`. 

If the character reconnected *with* the addon enabled, then it would just join the first available index again which would be `1`; or `5` if another addon connected to `1` first , which i now believe to be what you were talking about when you said it "making it worse" since if user was connected to any permanent channels in 6-8 or something your "LookingForGroup" channel could potentially bounce between 1,2,5,9 depending of the order the addons load in.

**Comment by juemrami** [comment]
My proposed solution is just join the channel permanently with a call to [`JoinPermanentChannel`](https://warcraft.wiki.gg/wiki/API_JoinPermanentChannel) instead.

**Comment by juemrami** [comment]
Okay, i added an additional bit of logic to check if the "General" channel is not where it usually use `/1`, if so it will output a chat message with a link that opens to the blizzard settings for re-organizing chat channels. 
This along with joining the LFG channel permanently will ensure the users preferred chat ordering is always respected going forward (on our end at least).

**images**
[https://i.imgur.com/SwZP0ew.jpeg](https://i.imgur.com/SwZP0ew.jpeg)

**Pull request merged**
