### PR TITLE
Fix "Combine sub-dungeon" option

### PR DESCRIPTION
**Pull request by juemrami**
Related Issues:
 - #201 
 
Here's with the option turned on
combined

And turned off
seperated

### CODE REVIEW

**Comment by juemrami** [comment]
The only major change is in the first commit, That alone fixed the issue. But while i was debugging i had to rename alot of the variables to understand what was going on with the code. Im suggesting we make them more readable for any future maintainers. 

I have some other changes, including type comments using [LuaLS](https://github.com/LuaLS/lua-language-server?tab=readme-ov-file) and their [annotation system](https://luals.github.io/wiki/annotations/) but i think its best to keep that tracked in its own PR in the future.

**Comment by juemrami** [comment]
In regards to commit 160ba9e. 

Not sure if you're still releasing builds for wotlk but I've noticed the last two releases on CF have only been for the classic client so i had these lines commented out originally.

**Comment by Vysci** [comment]
> Not sure if you're still releasing builds for wotlk but I've noticed the last two releases on CF have only been for the classic client so i had these lines commented out originally.

Not particularly mainly because I don't play wotlk so not sure about the current state of the add-on. If anyone still uses it I don't want to break it due to me not testing wotlk

**Comment by Vysci** [comment]
@juemrami it seems like the combine subdungeon option gets randomly unselected. Not sure of the trigger but had a few times where it became unchecked. It's fairly minor issue and could be due to me switching clients. Just something to keep an eye out to make sure it's not happening with other options

**Pull request merged**
