### PR TITLE
Remove unused dungeon tags for vanilla clients

### PR DESCRIPTION
**Pull request by juemrami**
Related Issues:
- #214 
- https://legacy.curseforge.com/wow/addons/lfg-group-finder-bulletin-board/?comment=619

### CODE REVIEW

**Comment by juemrami** [comment]
@Vysci This (d797a0f) is what i meant. 

You mentioned concerns about this happening early enough so that it doesnt cause any unwanted side effects. 

This code runs after `Dungeon.lua` and at the very end of `Tags.lua`. This is before `GBB.dungeonTagsLoc` is accessed by code in `Options.lua` and `GroupBulletinBoard.lua` (in that order)

The function `GBB.CreateTagListLOC` is itself initialized and called from `GroupBulletinBoard.lua` and would have the newly validated `dungeonTagsLoc` to insert into `GBB.tagList`

**Comment by juemrami** [comment]
The only side effect atm is from the reference in `Options.lua`

Here the `CreateEditBoxDungeon` dungeon attempts to index `GBB.dungeonTagsLoc["enGB"][Dungeon]`, where `Dungeon` can be a dungeon that was removed from the `dungeonTagsLoc` table.

This is "issue" due to this 
```lua
for index=1,GBB.ENDINGDUNGEONEND do
	CreateEditBoxDungeon(GBB.dungeonSort[index],"",445,200)
end
```

which atm iterates through all dungeons for whom an **integer** index is set in  the `dungeonSort` table (This happens in `Dungeon.lua`)

only error this seems to cause is a visual (bug/feature) where the tags for these unused dungeons fails to be generated in the editboxes for these removes dungeons.

examples:
before change
after change

**Comment by Vysci** [comment]
Concern being maintainability, less of a concern about currently breaking stuff, although worth making sure it doesn’t break with a non English client. 

Whats your concern with going with the builder pattern approach besides reminding you of Java

**Comment by juemrami** [comment]
When you mention maintainability concerns, what are you envisioning breaking/changing in the future for classic wow that would require a complete look over at this logic. 

As it stands, if you ever find a dungeon key was unintentionally removed, then you just have to make sure its part of either `GBB.SodPvpNames`, `GBB.VanillDungeonNames` or `GBB.Misc` (all hard coded lists), and if you dont want to modify those lists then you could include the key in the local `exceptions` table.

Worst case scenario that whole conditional code block could be deleted and the addon would still function as before (youd just need to ensure your not feeding `nil` to the sort functions again).

As for the builder pattern, its not something i really considered, ive never implemented one, only used them in external API's, im not sure how necessary it would be. What about the builder patterns do you like that you think would fit good here?

**Comment by Vysci** [comment]
I see. Builder is an older technique that is more prevalent in Java but it's essentially a way to assemble complex objects step by step with the attributes we want. It would like something like 

```
DungeonBuilder.withVanillaDungeons

if TBC:
 DungeonBuilder.withTbcDungeons
if Wotlk:
 DungeonBuilder.withTbcDungeons.withWotlkDungeons

DungeonBuilder.build (returns the build taglist)
```
The advantage here is that for each expansion it just simply adds on to the existing tag list. In case we remove or add some tags then everything is taken care of, no need to make sure it's present in any list. Don't need to have any additional logic of removing
it from the list. No extra tags would be showing up under search pattern either. Just overall makes it more maintainable 

As you already made the change, going to merge this. I do appreciate you going ahead and doing this and catching this issue.

**Comment by juemrami** [comment]
@Vysci Oh okay, i see what you have in mind. We could do this. It would be best to separate out the logic for each game version you plan to support. into its own own directory, i,e;
- `./data/classic.lua`
- `./data/wotlk.lua`
- `./data/cata.lua`

and then set up the builder logic in `dungeons.lua` to pull from the correct tables set up in mentioned files.

This is what i had in mind for #217 , but only planned on doing `./data/classic.lua` and `./data/cata.lua` because of limitations for how i planned on getting localized dungeon names programatically.

**Pull request merged**
