### PR TITLE
Temporary added reset window position button on popup-menu(right clic…

### PR DESCRIPTION
**Pull request by ista1024**
…k on minimap button)

 - Issue: https://github.com/Vysci/LFG-Bulletin-Board/issues/224
 - Added Localization property  "BtnResetWindow" on each locales
 - Tested: Click on "Reset Window Position" button on popup-menu
   1. Reset while opened or closed window ether.
   2. Close popup-menu after reset.
   3. No Lua error caused.

Screenshot 2024-05-02 181832

### CODE REVIEW

**Comment by Vysci** [comment]
I think this was fixed in https://github.com/Vysci/LFG-Bulletin-Board/pull/225

**Comment by juemrami** [comment]
I dont mind the option. 

I dont see any other way for a user to reset the window (for whatever reason) without a `/run` script.

**Comment by ista1024** [comment]
Thanks for considering about this pull request.
The issue has been fixed with the changes made in https://github.com/Vysci/LFG-Bulletin-Board/pull/225 as you know.

Additionally, I suggest providing an option to manually reset the position like [juemrami](https://github.com/juemrami) has mentioned above.

However, I'm not really sure if this is the right position.

Your feedback would be appreciated.

**Comment by Vysci** [comment]
@ista1024 
So I think this setting going on the minimap quick access doesn't make to o much sense. If it's an option on the minimap the expectation is that it's something that you use/change often, which I hope this is not the case. I think this makes more sense to put in the regular settings. 

The other thing you can just type `/gbb reset` @juemrami

**Comment by ista1024** [comment]
@Vysci 
Thanks for sharing your idea!
I was actually thinking about the same thing.

Even though it has been mentioned how to reset the window in about section in the regular settings, it might still be hard for users to find.
So, I'll close this pull request and put the option in the regular settings instead.

Your thoughts really helped.
Thanks again for your idea!

**Comment by ista1024** [comment]
@Vysci 
Thanks for sharing your idea!
I was actually thinking about the same thing.

Even though it has been mentioned how to reset the window in about section in the regular settings, it might still be hard for users to find.
So, I'll close this pull request and put the option in the regular settings instead.

Your thoughts really helped.
Thanks again for your idea!

**Pull request closed without merging**
