### PR TITLE
revert: re-add "migrate `DropDownMenu` to utilize `SavedVarRegistry`"

### PR DESCRIPTION
**Pull request by juemrami**
This is a re-implementation of #275, following @Vysci's reverts in #278 & #279

Id like some more info surrounding the issues you encountered that lead to the reversion, so i know at what point to debug. 
I've gone and checked the state of the addon in commits in #275, #276, #277 on SoD trying to find an error but no luck. 

I havent changed any code from these commits that i'm testing vs the original PR commits (rest of PR's will be submitted after this one), so any errors you encountered would still be in here, thats why i ask.

### CODE REVIEW

**Comment by juemrami** [comment]
Lets wait to merge these re-reversions until after these issues have been resolved

- #286 
- #287

**Comment by Vysci** [comment]
Let me see if I can reproduce it again. I should have captured the error.

**Comment by juemrami** [comment]
You said you were on SoD so i've been spending some time on there with these changes and havent gotten any errors. 
So they may have been related to a previous in-compatibility with the `DFC` changes that may have been fixed with the recent changes.

@Vysci. I'm going to re-merge these changes to get an alpha out CF and release em with 3.35

**Comment by Vysci** [comment]
Can’t remember if it was in SoD or if that was when I tried to make sure that my changes didn’t break Cata. 

I’m out of town until next week so can’t look

**Comment by juemrami** [comment]
Np. ill test it and get the changes out then. 👍

**Pull request merged**
